//! Tauri commands for dictionary and library operations.
//!
//! These commands expose the dictionary and library functionality to the frontend.
//! Commands are organized into feature-based submodules.

use rusqlite::Connection;
use std::sync::Mutex;

pub mod analysis;
pub mod dictionary;
pub mod known_words;
pub mod learning;
pub mod library;
pub mod settings;
pub mod speed;
pub mod user_dictionary;

/// Application state containing the database connection
pub struct AppState {
    pub db: Mutex<Connection>,
}

/// Error type for Tauri commands
#[derive(Debug, thiserror::Error)]
pub enum CommandError {
    #[error("Database error: {0}")]
    Database(String),

    #[error("Not found: {0}")]
    NotFound(String),

    #[error("IO error: {0}")]
    Io(String),

    #[error("Invalid input: {0}")]
    InvalidInput(String),
}

impl serde::Serialize for CommandError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(&self.to_string())
    }
}

pub type CommandResult<T> = Result<T, CommandError>;

// Re-export all commands (and the hidden __cmd__* wrappers generated by
// #[tauri::command]) so that `commands::xyz` and `commands::__cmd__xyz`
// paths used by tauri::generate_handler! in lib.rs continue to resolve.
pub use analysis::*;
pub use dictionary::*;
pub use known_words::*;
pub use learning::*;
pub use library::*;
pub use settings::*;
pub use speed::*;
pub use user_dictionary::*;
